name: SDHubCore
version: IR-1.0
api: [3.0.0-ALPHA12]
main: SDHubCore\MainIR
author: StrikeDevelopment & xXCaulDevsYT

commands:
    hub:
        description: Return To Hub
        permission: sd.hub
    sethub:
         description: Set a main hub to location point
         permission: sd.sethub
    fly:
         description: Fly ability on command
         permission: sd.fly
    gmc:
         description: Change your gamemode to Creative
         permission: sd.gamemode
    gms:
         description: Change your gamemode to Survival
         permission: sd.gamemode
    gma:
         description: Change your gamemode to Adventure
         permission: sd.gamemode
    gmspc:
         description: Change your gamemode to Spectator
         permission: sd.gamemode
